spring:
  datasource:
    url: jdbc:mariadb://221.161.177.193:3306/smart_shoes
    username: root
    password: Shoenet1!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 운영 환경에서는 스키마 변경을 수동으로 관리
    show-sql: true

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


